- name: Ensure yum  work with proxy(http)
  lineinfile: dest=/etc/yum.conf state=present regexp="{{ http_proxy }}" insertafter=EOF line="proxy={{ http_proxy }}"
  ignore_errors: yes
  tags: [ preinstall ]  
# #yum install https://github.com/cybertec-postgresql/patroni-packaging/releases/download/1.6.0-1/patroni-1.6.0-1.rhel7.x86_64.rpm
- name: Install epel-release repo
  yum: 
    #name: ['postgresql11.x86_64', 'pgbouncer.x86_64', 'pgbackrest.x86_64', 'repmgr11.x86_64', 'pg_cron_11', 'pgcenter', 'postgresql11-contrib.x86_64', 'python2-psycopg2.x86_64'] 
    name: ['epel-release']
    update_cache: true
    install_weak_deps: true   
    state: installed
  environment:
    HTTP_PROXY: '{{ http_proxy }}'
    HTTPS_PROXY: '{{ http_proxy }}'  
  when: skip_host is not defined
  tags: [ install ]  
- name: Install patroni package
  yum: 
    #name: ['postgresql11.x86_64', 'pgbouncer.x86_64', 'pgbackrest.x86_64', 'repmgr11.x86_64', 'pg_cron_11', 'pgcenter', 'postgresql11-contrib.x86_64', 'python2-psycopg2.x86_64'] 
    name: ['https://github.com/cybertec-postgresql/patroni-packaging/releases/download/1.6.0-1/patroni-1.6.0-1.rhel7.x86_64.rpm']
    update_cache: true
    install_weak_deps: true   
    state: installed
  environment:
    HTTP_PROXY: '{{ http_proxy }}'
    HTTPS_PROXY: '{{ http_proxy }}'  
  when: skip_host is not defined
  tags: [ install ]  
  
# - pip:
    # name: patroni
  # environment:
    # HTTP_PROXY: '{{ http_proxy }}'
    # HTTPS_PROXY: '{{ http_proxy }}'  
  # tags: [ install ] 

- name: Makes /home/{{ postgresql_user }}/patroni.yml
  template: src=patroni.yml.j2 dest=/home/{{ postgresql_user }}/patroni.yml mode=0750 owner={{ postgresql_user }} group={{ postgresql_group }}
  #notify: restart patroni service  
  when: skip_host is not defined  

- name: Configure patroni.service at /usr/lib/systemd/system/patroni.service
  lineinfile: 
    dest: "/usr/lib/systemd/system/patroni.service"
    regexp: "^Environment=PATRONI_CONFIG_LOCATION=.*$" 
    line: "Environment=PATRONI_CONFIG_LOCATION=/home/{{ postgresql_user }}/patroni.yml"
    state: present
  ignore_errors: yes
  when: skip_host is not defined  
  tags: [ tested, install ]  
  
- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes
    
- name: Start and enable service patroni.service
  service: 
    name: patroni.service 
    state: restarted
    enabled: yes
  when: 
    - skip_host is not defined  
    