- name: Makes /home/postgres/logrotate.cfg
  template: src=template/pglogrotate.cfg dest=/home/postgres/logrotate.cfg mode=0750 owner={{ postgresql_user }} #group={{ postgresql_group }} mode=750
  tags: configure
#  template: 
#    src:templates/pglogrotate.cfg 
#    dest:/etc/logrotate.d/pglogrotate.cfg 
##    owner:root 
#    group:root

- name: Get groups info from {{ postgresql_user }} user
  user:
    name: "{{ postgresql_user }}"
    state: present
  register: user_groups

- name: Remove {{ postgresql_user }} user from dba group
  become: true
  command: "gpasswd -d '{{ postgresql_user }}' dba"
  when: user_groups.groups is defined and 'dba' in user_groups.groups
 
- name: Ensure group "dba" NOT exists
  group:
    name: "dba"
    state: absent
  when: user_groups.groups is defined and 'dba' in user_groups.groups
  tags: [ tested, preinstall ]
  
- name: Creates a cron job for logrotate once a day at midnight
  cron:
    name: logrotate postgres log
    minute: "0"
    hour: "0"
    user: postgres
    job: "/usr/sbin/logrotate -f /home/postgres/logrotate.cfg --state /home/postgres/logrotate-state"
